### PR TITLE
Tidying

### PR DESCRIPTION
**Pull request by alex-blair**
Tidied indenting of pristine-zen-garden.html

### CODE REVIEW

**Comment by andre-charb** [comment]
Hi Alix, 
All looks good, just one random line break unlike the others on line 127 and 128 to fix.  Once this is corrected, I can merge your pull request.
Cheers, Andre

**Comment by alex-blair** [comment]
Hi @andre-charb - I've corrected those lines now. Thanks for reviewing!

**Comment by andre-charb** [comment]
All merged!  Deleting branch.

**Comment by alex-blair** [comment]
Thanks @andre-charb!

**Pull request merged**
